In [1]:
import pandas as pd
import numpy as np
#import matplotlib
#import matplotlib.pyplot as plt
#import plotly.express as px
#import plotly.graph_objects as go
#import seaborn as sns
import os


train_df = pd.read_csv(r'..\Training datasets\train.csv')
train_df.head(10)

C:\Users\PC\AppData\Local\Temp\ipykernel_8036\2231784034.py:11: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv(r'..\Training datasets\train.csv')

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
5,6,5,2015-07-31,5651,589,1,1,0,1
6,7,5,2015-07-31,15344,1414,1,1,0,1
7,8,5,2015-07-31,8492,833,1,1,0,1
8,9,5,2015-07-31,8565,687,1,1,0,1
9,10,5,2015-07-31,7185,681,1,1,0,1

In [2]:
test_df = pd.read_csv(r'..\Training datasets\test.csv')
test_df.head(10)

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0
5   6     10          4  2015-09-17   1.0      1            0              0
6   7     11          4  2015-09-17   1.0      1            0              0
7   8     12          4  2015-09-17   1.0      1            0              0
8   9     13          4  2015-09-17   1.0      1            0              0
9  10     14          4  2015-09-17   1.0      1            0              0

In [3]:
store_df = pd.read_csv(r'..\Training datasets\store.csv')
store_df.head(10)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN

In [4]:
sample_submission_df = pd.read_csv(r'..\Training datasets\sample_submission.csv')
store_df.head(10)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN

In [5]:
# Merging the information from store_df to train_df and test_df

rossman_sales_train = train_df.merge(store_df, how='left', on='Store')
rossman_sales_test = test_df.merge(store_df, how='left', on='Store')

rossman_sales_train

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [6]:
rossman_sales_test

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
41084,41085,1112,6,2015-08-01,1.0,0,0,0,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
41085,41086,1113,6,2015-08-01,1.0,0,0,0,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
41086,41087,1114,6,2015-08-01,1.0,0,0,0,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
41087,41088,1115,6,2015-08-01,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

# DATA CLEANING OF THE TRAINING DATA SET

PREPROCESSING AND FEATURE ENGINEERING

In [7]:
rossman_sales_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  str
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  str
 10  Assortment                 1017209 non-null  str
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   str
dtypes: float64(5), int64(8), object(1), str(4)
memory usage: 159.1+ MB

STEP 1 : CONVERTING THE DATE COLUMN INTO THE DATE DATATYPE AND EXTRACTING DIFFERENT PARTS OF THE DATE

In [8]:
# Initializing the general function to perform date operations

def split_date(df):
    df['Date'] = pd.to_datetime(df['Date']) # Since the date feature is a string data type, use this to convert it to datetime datatype
    df['Year'] = df.Date.dt.year # Create the Year feature from the date feature
    df['Month'] = df.Date.dt.month # Create the Month feature from the date feature
    df['Day'] = df.Date.dt.day # Create the Day feature from the date feature
    df['WeekOfYear'] = df.Date.dt.isocalendar().week
    
split_date(rossman_sales_train)
split_date(rossman_sales_test)

# You can check using these: 
# rossman_sales_train.head(6)
# rossman_sales_test.head(6)

In [9]:
rossman_sales_train.head(6)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,WeekOfYear
0,1,5,2015-07-31,5263,555,1,1,0,1,c,...,9.0,2008.0,0,NaN,NaN,NaN,2015,7,31,31
1,2,5,2015-07-31,6064,625,1,1,0,1,a,...,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2015,7,31,31
2,3,5,2015-07-31,8314,821,1,1,0,1,a,...,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2015,7,31,31
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,...,9.0,2009.0,0,NaN,NaN,NaN,2015,7,31,31
4,5,5,2015-07-31,4822,559,1,1,0,1,a,...,4.0,2015.0,0,NaN,NaN,NaN,2015,7,31,31
5,6,5,2015-07-31,5651,589,1,1,0,1,a,...,12.0,2013.0,0,NaN,NaN,NaN,2015,7,31,31

THE FEATURE 'OPEN'

Identifies whether the store is open on a certain date or not

yes -1 (Signifies presence of sales)

no - 0 (Most likely there are no sales)

In [10]:
# TO CONFIRM WHETHER THERE ARE NO SALES WHEN THE STORE IS CLOSED

rossman_sales_train[rossman_sales_train['Open'] == 0].Sales.value_counts()

Sales
0    172817
Name: count, dtype: int64

DECISION: IN THE TRAINING DATASET, REMOVE THE INSTANCES(ROWS) WHERE THE STORE IS CLOSED SINCE THIS WOULD NOT YIELD ANY SALES

IN THE TEST DATASET, IT REMAINS CONSTANT SINCE WE NEED TO PREDICT USING IT.

In [11]:
# Removing all the instances in the training dataset where the store was closed since there will be no sales 
rossman_sales_train = rossman_sales_train[rossman_sales_train['Open'] == 1].copy()

FEATURE ENGINEERING ON COMPETITION

1. CompetitionDistance - distance in meters to the nearest competitor store

2. CompetitionOpenSince[Month/Year] - gives the approximate year and month of the time the nearest competitor was opened

In [12]:
# Use the CompetitionOpenSince[Month/Year] columns from the store_df to compute the number of months for which a competitor has been open near the store

def comp_months(df):
    df['CompetitionOpen'] = 12 * (df.Year - df.CompetitionOpenSinceYear) + (df.Month - df.CompetitionOpenSinceMonth)
    df['CompetitionOpen'] = df['CompetitionOpen'].map(lambda x: 0 if x < 0 else x).fillna(0)
    
    return df

The CompetitionOpen column represents the total number of months a competitor has been active and operating near a specific store at the time of a given sales record.

Time-Aware Metric: It is not a fixed number. It changes dynamically depending on the date of the sales record.

Zero Value Meaning: A value of 0 means the competitor has not opened yet, opened in the current month, or the opening date is unknown.

Data Unit: The final output is an integer representing time measured strictly in months.

This is done because:
   1. Raw dates (like 2025 or March) are hard for algorithms to interpret. A single continuous number (like 14 months) is much easier for a machine learning model to read.

   2. Retail stores often see a drop in sales when a competitor first opens nearby. This column helps the model learn if a competitor is brand new (low number) or long-established (high number).


THE LAMBDA FUNCTION: 

1. Handle Future Dates: 

If the competitor opens after the transaction date, the subtraction results in a negative number. The lambda function forces any negative values to 0 (meaning 0 months open).Handle Missing Data: The .fillna(0) converts any NaN (missing) values to 0, which happens if the opening month or year data was originally blank.

2. Handle Missing Data: 

The .fillna(0) converts any NaN (missing) values to 0, which happens if the opening month or year data was originally blank.

In [20]:
# Sneek peak of the column implementation

rossman_sales_train = comp_months(rossman_sales_train)
rossman_sales_test = comp_months(rossman_sales_test)

In [21]:
# FOR INSPECTION OF THE DATASET TO CHECK IF THE CHANGES ARE IN EFFECT

# rossman_sales_train.head(10)
# rossman_sales_test.head(10)

FEATURE ENGINEERING ON PROMOTION

Adding some additional columns to indicate how long a store has been running Promo2 and whether a new round of Promo2 starts in the current month

Promo - indicates whether a store is running a promo on that day

Promo2 - Promo2 is a continuing and consecutive promotion for some stores: 0 = store is not participating, 1 = store is participating

Promo2Since[Year/Week] - describes the year and calendar week when the store started participating in Promo2

PromoInterval - describes the consecutive intervals Promo2 is started, naming the months the promotion is started anew. E.g. "Feb,May,Aug,Nov" means each round starts in February, May, August, November of any given year for that store

Rossmann store runs a repeating promotion called Promo2. The things we want to know about each row (a store on a specific date) are:

How long has Promo2 been running at this store? (in months)

Is this month one where a new round of Promo2 just kicked off?

In [22]:
def check_promo_month(row):
    month2str = {
        1:'Jan',
        2:'Feb',
        3:'Mar',
        4:'Apr',
        5:'May',
        6:'Jun',
        7:'Jul',
        8:'Aug',
        9:'Sept',
        10:'Oct',
        11:'Nov',
        12:'Dec'
    }
    
    try:
        # Dataset stores a string like "Jan,Apr,Jul,Oct" telling you which months a new promo round begins. This line breaks that string into a list: ['Jan', 'Apr', 'Jul', 'Oct'].
        
        months = (row['PromoInterval'] or '').split(',')
        
        # If Promo2 is already running here, AND this row's month is one of the months listed in that string — say yes (1). Otherwise, say no (0)
        
        if row['Promo2Open'] and month2str[row['Month']] in months:
            return 1
        else:
            return 0
        
    except Exception:
        return 0
    
def promo_cols(df):
    # Months since Promo2 was open
    # take the year gap, turn it into months (×12), then add the leftover week gap. It's a rough "how many months has this promo been live" number.
    # If the number comes out negative (meaning Promo2 hadn't started yet on this date), just call it 0.
    # If it's missing, call it 0 too.
    # Then multiply by Promo2 (which is 1 if the store participates, 0 if not) — so stores that never signed up for Promo2 automatically get 0, no matter what.
    
    df['Promo2Open'] = 12 * (df.Year - df.Promo2SinceYear) + (df.WeekOfYear - df.Promo2SinceWeek)* 7 / 30.5
    df['Promo2Open'] = df['Promo2Open'].map(lambda x: 0  if x < 0 else x).fillna(0) * df['Promo2']
    
    # Checking whether a new round of promotions was started in the current month
    df['IsPromo2Month'] = df.apply(check_promo_month, axis=1) * df['Promo2']
    
    return df

In [23]:
# FOR QUICK INSPECTION

# rossman_sales_train= promo_cols(rossman_sales_train)
# rossman_sales_test = promo_cols(rossman_sales_test)

# rossman_sales_train

# SELECTING THE INPUT AND TARGET COLUMNS

USING THE TRAINING DATASET

In [25]:
#rossman_sales_train.columns
rossman_sales_train.info()

<class 'pandas.DataFrame'>
Index: 844392 entries, 0 to 1017190
Data columns (total 25 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Store                      844392 non-null  int64
 1   DayOfWeek                  844392 non-null  int64
 2   Date                       844392 non-null  datetime64[us]
 3   Sales                      844392 non-null  int64
 4   Customers                  844392 non-null  int64
 5   Open                       844392 non-null  int64
 6   Promo                      844392 non-null  int64
 7   StateHoliday               844392 non-null  object
 8   SchoolHoliday              844392 non-null  int64
 9   StoreType                  844392 non-null  str
 10  Assortment                 844392 non-null  str
 11  CompetitionDistance        842206 non-null  float64
 12  CompetitionOpenSinceMonth  575773 non-null  float64
 13  CompetitionOpenSinceYear   575773 non-null  float64
 14  Promo2                     844392 non-null  int64
 15  Promo2SinceWeek            421085 non-null  float64
 16  Promo2SinceYear            421085 non-null  float64
 17  PromoInterval              421085 non-null  str
 18  Year                       844392 non-null  int32
 19  Month                      844392 non-null  int32
 20  Day                        844392 non-null  int32
 21  WeekOfYear                 844392 non-null  UInt32
 22  CompetitionOpen            844392 non-null  float64
 23  Promo2Open                 844392 non-null  float64
 24  IsPromo2Month              844392 non-null  int64
dtypes: UInt32(1), datetime64[us](1), float64(7), int32(3), int64(9), object(1), str(3)
memory usage: 163.4+ MB

In [36]:
# SEPARATING THE INPUT FEATURES FROM THE TARGET FEATURES

input_cols = [
    'Store', 'DayOfWeek', 'Promo', 'Promo2',
    'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
    'CompetitionDistance', 'Year', 'Month', 'Day','WeekOfYear', 'CompetitionOpen', 'Promo2Open', 'IsPromo2Month'
    ]

target_col = 'Sales'

inputs = rossman_sales_train[input_cols].copy()
targets = rossman_sales_train[target_col].copy()

# Create a copy for the test dataset

test_inputs = rossman_sales_test[input_cols].copy()

CHECKING THE NUMERIC AND CATEGORICAL FEATURES

In [37]:
numeric_cols = [
    'Store', 'Promo', 'Promo2',
    'SchoolHoliday','CompetitionDistance', 'Year', 
    'Month', 'Day','WeekOfYear', 
    'CompetitionOpen', 'Promo2Open', 'IsPromo2Month'
    ]

categorical_cols = ['StateHoliday', 'StoreType', 'Assortment', 'DayOfWeek']

IMPUTING MISSING NUMERICAL DATA

In [38]:
inputs[numeric_cols].isna().sum()

Store                     0
Promo                     0
Promo2                    0
SchoolHoliday             0
CompetitionDistance    2186
Year                      0
Month                     0
Day                       0
WeekOfYear                0
CompetitionOpen           0
Promo2Open                0
IsPromo2Month             0
dtype: int64

In [39]:
test_inputs[numeric_cols].isna().sum()

Store                   0
Promo                   0
Promo2                  0
SchoolHoliday           0
CompetitionDistance    96
Year                    0
Month                   0
Day                     0
WeekOfYear              0
CompetitionOpen         0
Promo2Open              0
IsPromo2Month           0
dtype: int64

In [41]:
# You can fill the competition distance with the maximum value to show that it is really far away
max_distance = inputs['CompetitionDistance'].max() # Find the maximum  value in training
print('THE MAXIMUM DISTANCE IS: ', max_distance)

inputs['CompetitionDistance']=inputs['CompetitionDistance'].fillna(max_distance)
test_inputs['CompetitionDistance']=test_inputs['CompetitionDistance'].fillna(max_distance)

THE MAXIMUM DISTANCE IS:  75860.0

SCALING THE NUMERIC COLUMNS ON THE 0-1 RANGE

In [44]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

# Initializing and fitting the scaler only on the training inputs
scaler = MinMaxScaler().fit(inputs[numeric_cols])

# Now tranforming both on the training and test inputs
inputs[numeric_cols] = scaler.transform(inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

ENCODING CATEGORICAL COLUMNS

In [54]:
# TO CHECK THE COLUMNS THAT HAVE MIXED DATA TYPES

#for col in categorical_cols:
    #types = inputs[col].apply(type).unique()
    #if len(types) > 1:
        #print(f"Column '{col}' has mixed types: {types}")

# Cast the  categorical columns explicitly to string
inputs[categorical_cols] = inputs[categorical_cols].astype(str)

# Force test data categorical columns to strings to match training data format
test_inputs[categorical_cols] = test_inputs[categorical_cols].astype(str)


# Initializing the encoder and fitting the training categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore').fit(inputs[categorical_cols])

# GETTING THE NEW ENCODED FEATURE NAMES
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))
encoded_cols

# Now transforming the encoded columns both on the training and test inputs
inputs[encoded_cols] = encoder.transform(inputs[categorical_cols])
test_inputs[encoded_cols] = encoder.transform(test_inputs[categorical_cols])

FINAL PREPARED TRAINING AND TESTING INPUT SETS

In [55]:
X_train = inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]